config/routes.rb
Rails.application.routes.draw do
  resources :languages
  resources :writers
  resources :stories

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  delete '/stories/:id', to: 'stories#destroy', as: 'delete_story'

  get'/stories/:id/development', to: "stories#development", as: 'development'
  post'/stories/:id/development', to: "stories#savedevelopment", as: 'savedevelopment'

  get'/stories/:id/twist', to: "stories#twist", as: 'twist'
  post'/stories/:id/twist', to: "stories#savetwist", as: 'savetwist'

  get'/stories/:id/conclusion', to: "stories#conclusion", as: 'conclusion'
  post'/stories/:id/conclusion', to: "stories#saveconclusion", as: 'saveconclusion'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :story_languages
  has_many :stories, through: :story_languages
  validates :name, presence: true
end

app/models/story.rb
require "google/cloud/translate"
require "google/cloud/storage"

class Story < ApplicationRecord
  has_many :story_writers
  has_many :writers, through: :story_writers
  has_many :story_languages
  has_many :languages, through: :story_languages
  validates :title, presence: true
  validates :daimei, presence: true
end

app/models/story_language.rb
class StoryLanguage < ApplicationRecord
  belongs_to :story
  belongs_to :language
end

app/models/story_writer.rb
class StoryWriter < ApplicationRecord
  belongs_to :writer
  belongs_to :story
end

app/models/translate_helper.rb
require "google/cloud/translate"
require "google/cloud/storage"

class TranslateHelper

  def initialize
    @google_translation_instance = set_up_google_translation_instance
  end

  def translate_text(text, lng)
    @google_translation_instance.translate(text, to: lng)
  end
  # def google_storage_instance
  #   storage = Google::Cloud::Storage.new project: 'jinglish-stories', keyfile: "/Users/flatironschool/Development/code/rails/natsuki_rosa_website/app/Jinglish-Stories-f3523a8500d2.json"
  # end
  private

  def set_up_google_translation_instance
    Google::Cloud::Translate.new(
      project: 'shiba-golden'
      keyfile:
    )
  end
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :story_writers
  has_many :stories, through: :story_writers
  validates :pen_name, presence: true, uniqueness: true
  validates :pen_name, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_logged_in?, :current_writer

  def current_writer
    if session[:writer_id]
      @writer = Writer.find(session[:writer_id])
    end
  end

  def is_logged_in?
    !!current_writer
  end

end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :find_language, only: [:show, :edit, :update]

  def index
    @languages = Language.all
  end

  def show
  end

  def edit
  end

  def update
    if @language.update(language_params)
      redirect_to @language
    else
      render :edit
    end
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      redirect_to @language
    else
      render :new
    end
  end

  def destroy
    Language.destroy(params[:id])
    redirect_to languanges_path
  end

  private

  def find_language
    @language = Language.find(params[:id])
  end

  def language_params
    params.require(:language).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @writer = Writer.find_by(pen_name: params[:pen_name])
      if @writer && @writer.authenticate(params[:password])
        session[:writer_id] = @writer.id
        redirect_to stories_path
      else
        redirect_to login_path
      end
  end

  def destroy
    session[:writer_id] = nil
    redirect_to login_path
  end

  private

  def authorized
      redirect_to login_path unless session[:writer_id]
  end
end

app/controllers/stories_controller.rb
require "google/cloud/translate"
require "google/cloud/storage"

class StoriesController < ApplicationController
  before_action :authorized
  before_action :find_story, only: [:show, :edit, :update, :beginning, :savebeginning, :development, :savedevelopment, :twist, :savetwist, :conclusion, :saveconclusion, :japanesestory]

  def index
    @stories = Story.all
  end

  def show
    translate_helper = TranslateHelper.new
    @portuguesestorytitle = translate_helper.translate_text("#{@story.title}", 'pt').text
    @portuguesestory = translate_helper.translate_text("#{@story.beginning} #{@story.development} #{@story.twist} #{@story.conclusion}", 'pt').text
    @spanishstorytitle = translate_helper.translate_text("#{@story.title}", 'es').text
    @spanishstory = translate_helper.translate_text("#{@story.beginning} #{@story.development} #{@story.twist} #{@story.conclusion}", 'es').text
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    translate_helper = TranslateHelper.new
    translation = translate_helper.translate_text(story_params[:beginning],'ja').text
    @story[:ki] = translation
    second_translate_helper = TranslateHelper.new
    second_translation = second_translate_helper.translate_text(story_params[:title],'ja').text
    @story[:daimei] = translation
      if @story.save
        redirect_to development_path(@story)
      else
        render :new
      end
  end

  def development
    render :development
  end

  def savedevelopment
    if @story.update(story_params)
      translate_helper = TranslateHelper.new
      translation = translate_helper.translate_text(story_params[:shou],'en').text
      @story[:development] = translation
      @story.save
      redirect_to twist_path(@story)
    else
      redirect_to :development
    end
  end

  def twist
    render :twist
  end

  def savetwist
    if @story.update(story_params)
      translate_helper = TranslateHelper.new
      translation = translate_helper.translate_text(story_params[:twist],'ja').text
      @story[:ten] = translation
      @story.save
      redirect_to conclusion_path(@story)
    else
      redirect_to :twist
    end
  end

  def conclusion
    render :conclusion
  end

  def saveconclusion
    if @story.update(story_params)
      translate_helper = TranslateHelper.new
      translation = translate_helper.translate_text(story_params[:ketsu],'en').text
      @story[:conclusion] = translation
      @story.save
      redirect_to story_path(@story)
    else
      redirect_to :twist_path
    end
  end

  def edit
  end

  def update
    if @story.update(story_params)
      redirect_to @story
    else
      render :edit
    end
  end

  def destroy
    Story.destroy(params[:id])
    redirect_to stories_path
  end

  private

  def find_story
    @story = Story.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:title, :beginning, :development, :twist, :conclusion, :daimei, :ki, :shou, :ten, :ketsu)
  end

  def authorized
      redirect_to login_path unless session[:writer_id]
  end

end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :authorized, except: [:new, :create]
  before_action :find_writer, only: [:show, :edit, :update]

  def index
    @writers = Writer.all
  end

  def show
  end

  def new
    @writer = Writer.new
  end

  def create
    @writer = Writer.new(writer_params)
    if @writer.save
      redirect_to login_path
      redirect_to @writer
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @writer.update(writer_params)
      redirect_to @writer
    else
      render :edit
    end
  end

  def destroy
    Writer.destroy(params[:id])
    redirect_to writers_path
  end

  private

  def authorized
      redirect_to login_path unless session[:writer_id]
  end

  def find_writer
    @writer = Writer.find(params[:id])
  end

  def writer_params
    params.require(:writer).permit(:pen_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/story_languages_helper.rb
module StoryLanguagesHelper
end

app/helpers/story_writers_helper.rb
module StoryWritersHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/languages/index.html.erb
<h2>All LANGUAGES</h2>

<ul>
<% @languages.each do |language| %>
<%=link_to language.name, language_path(language) %>
<br>
<% end %>
</ul>

<%= link_to 'Create A New Language!', new_language_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rosanatsukimod2project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="fixed-background-img"></div>
    <div class="container-fluid">
      <nav>
        <h1>Shiba Golden</h1>
        <%  if current_writer %>
          <%= form_tag "/logout", method: :delete do %>
          <%= submit_tag "Logout" %>
        <% end %>
        <!-- If not logged in, show login -->
      <% else %>
        <%= link_to "log in", login_path %>
      <% end %>
    </nav>
    <%= yield %>
  </div>
</body>
</html>

app/views/stories/conclusion.html.erb
これまでのお話はこちら：
<h2><%= @story.ki %></h2>
<h2><%= @story.shou %></h2>
<h2><%= @story.ten %></h2>

<h2><%= @story.beginning %></h2>
<h2><%= @story.development %></h2>
<h2><%= @story.twist %></h2>

ここに次の物語を書いてください＃＃＃＃：
<%= form_tag saveconclusion_path(@story), method: :post do %>
  <%= label_tag '承（conclusion）' %>
  <%= text_area_tag 'story[ketsu]' %>
  <%= submit_tag '保存して次の物語にすすむ＃＃＃＃ket' %>
<% end %>

app/views/stories/development.html.erb
<h1>承,"the development"</h1>
<h4>これまでのお話はこちら：</h4>
<h2><%= @story.beginning %></h2>
<h2><%= @story.ki %></h2>

<h4>ここに次の物語を書いてください：</h4>
<%= form_tag savedevelopment_path(@story), method: :post do %>
  <%= text_area_tag 'story[shou]' %>
  <%= submit_tag '保存して次の物語にすすむ' %>
<% end %>

app/views/stories/edit.html.erb
<style>

  .edit-story-form {
    border-radius: 25px;
    background-color: rgba(155, 155, 155, 0.5);
    min-width: 450px;
    margin: 25px auto;
    padding: 0 35px;
    font-size: 30px;
    text-align: center;
    transition: 0.3s;
  }

  .edit_story {
    display: flex
  }

  .english-form {
    width: 40%
  }

  .jap-form {
    width: 40%
  }
</style>

<div class="edit-story-form">
  <%= form_for(@story) do |f| %>
  <div class="english-form">
    <%= f.label :title %>
    <h1><%= f.text_area :title %></h1>
    <%= f.label :beginning %>
    <h2><%= f.text_area :beginning %></h2>
    <%= f.label :development %>
    <h2><%= f.text_area :development %></h2>
    <%= f.label :twist %>
    <h2><%= f.text_area :twist %></h2>
    <%= f.label :conclusion %>
    <h2><%= f.text_area :conclusion %></h2>
    <%= f.submit %><br><br><br>
  </div>

  <div class="jap-form">
    <%= f.label "題名" %>
    <h1><%= f.text_area :daimei %></h1>
    <%= f.label "起" %>
    <h2><%= f.text_area :ki %></h2>
    <%= f.label "承" %>
    <h2><%= f.text_area :shou %></h2>
    <%= f.label "転" %>
    <h2><%= f.text_area :ten %></h2>
    <%= f.label "結" %>
    <h2><%= f.text_area :ketsu %></h2>
    <%= f.submit "物語を更新する"%>
  </div>
<% end %>

</div>

app/views/stories/index.html.erb
<style>

.flex-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  background-color: transparent;
}

.story-card {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  border-radius: 25px;
  background-color: rgba(155, 155, 155, 0.7);
  width: 300px;
  height: 300px;
  margin: 25px;
  font-size: 30px;
  text-align: center;
  transition: 0.3s
}

.story-card:hover {
  background-color: rgba(55, 155, 155, 0.95);
  transform: scale(1.15);
}

.story-card a {
  color: #FFFFFF;
}

.story-card a:hover {
  text-decoration: none;
}
</style>

<div class="row">
  <br>
  <p><center><h2>Welcome to the library! Feel free to read a story.</h2><br></center></p>
  <p><center><h4>物語の図書館へようこそ！物語を選んでください。</h4><br>
  </center></p>
  <div class="flex-container">
    <% @stories.each do |story| %>
    <div class="story-card">
      <%= link_to "#{story.title}\r\n#{story.daimei}", story_path(story) %>
    </div>
    <% end %>
  </div>
  <p><center><h2><%= link_to 'Write your own story' + ' 物語を書く', new_story_path %></h2>
  </center></p>
</div>

app/views/stories/new.html.erb
<style>

  .new-story-form {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
    border-radius: 25px;
    background-color: rgba(155, 155, 155, 0.5);
    height: 900px;
    min-width: 450px;
    margin: 25px auto;
    padding: 0 35px;
    font-size: 30px;
    text-align: center;
    transition: 0.3s;
  }

  .new-story-header h1:nth-child(2) {
    margin-top: 0;
  }


  h5 {
    margin-top: 0;
  }


</style>

<div class="new-story-form">

  <div class="new-story-header">
    <h1>起</h1>
    <h1>"The Beginning"</h1>
  </div>
  <%= form_for(@story) do |f| %>
  <h3>What is the title of your story?</h3>
  <%= f.text_field :title %>
  <h3>Here is an example of a story's beginning:<br>
    "Once upon a time there was a mouse who lived in a jelly donut."<br>
    <br>Please write the beginning of your story:</h3><br>
  <%= f.text_area :beginning %><br>
  <h3>On the next page your partner will see the beginning of your story translated into Japanese and have the option to write the next section. Are you ready to move on?</h3><br>
  <h5>物語のタイトルを記入してください。</h5>
  <%= f.text_field :title %>
  <h3>Here is an example of a story's beginning:<br>
    "Once upon a time there was a mouse who lived in a jelly donut."<br>
  <h5>さっそく物語を書き始めてみましょう。<br>例）"むかしむかし、ジェリードーナッツの中にねずみが住んでいました。"</h5><br>
    <br>Please write the beginning of your story:</h3><br>
    <h5>ここに物語のはじめを記入してください。</h5><br>
  <%= f.text_area :beginning %><br>
  <h3>On the next page your partner will see the beginning of your story translated into Japanese and have the option to write the next section. Are you ready to move on?</h3><br>
  <h5>次のページでは、あなたのパートナーがあなたが書いた物語の日本語訳を確認し、物語の続きを書くことができます。準備はよろしいですか？</h5><br>
  <%= f.submit "yes, we're ready"%>
<% end %>
</div>

app/views/stories/show.html.erb
<br>
<h1>"<%= @story.title %>"</h1>

<br>
 <%= "#{@story.beginning} #{@story.development} #{@story.twist} #{@story.conclusion}" %>
<br><br><br><br><br>
<h1>"<%= @story.daimei %>"</h1>
<br>
 <%= "#{@story.ki} #{@story.shou} #{@story.ten} #{@story.ketsu}" %>
<br><br><br><br><br>
<h1>"<%= @spanishstorytitle %>"</h1>
<br>
 <%= @spanishstory %>
<br><br><br><br><br>
<h1>"<%= @portuguesestorytitle %>"</h1>
<br>
 <%= @portuguesestory %>
<br><br><br><br><br>
<hr>
<hr>

<%= link_to 'Edit This Story', edit_story_path(@story) %>
<%= link_to '物語を編集する', edit_story_path(@story) %>
<br>
<%= link_to "Delete This Story", @story, method: :delete, data: { confirm: "Do you really want to delete this beautiful story?" } %>
<%= link_to "物語を削除する", @story, method: :delete, data: { confirm: "Do you really want to delete this story?" } %>
<br>
<%= link_to 'See All Stories', stories_path %>
<%= link_to 'すべての物語をみる', stories_path %>
<br>
<%= link_to 'See All Writers', writers_path %>
<%= link_to 'すべての物語をみる', writers_path %>

app/views/stories/twist.html.erb
<h1>転,"the twist"</h1>
<h4>This is your story so far:</h4>
<h2><%= @story.ki %></h2>
<h2><%= @story.shou %></h2>

<h3><%= @story.beginning %></h3>
<h3><%= @story.development %></h3>

<h4>Now write the twist:<h4>
<%= form_tag savetwist_path(@story), method: :post do %>
  <%= label_tag "twist" %>
  <%= text_area_tag 'story[twist]' %>
  <%= submit_tag 'We are ready to write the conclusion'  %>
<% end %>

app/views/writers/edit.html.erb
EDIT THIS WRITER!

<%= form_for @writer do |f| %>
<%= f.label :pen_name %>
<%= f.text_field :pen_name %>
<br>
<%= f.label :password %>
<%= f.text_field :password %>
<br>
<%= f.submit %>
<% end %>

app/views/writers/index.html.erb
<h2>All WRITERS</h2>

<ul>
<% @writers.each do |writer| %>
<%= link_to writer.pen_name, writer_path(writer) %>
<li>
<%= link_to writer.pen_name, writer_path(writer) %>
</li>
<br>
<% end %>
</ul>

<%= link_to 'Create A New Writer!', new_writer_path %>
<%= link_to 'Edit This Writer!', edit_writer_path %>
<%= link_to 'See All Stories!', edit_writer_path %>

app/views/writers/new.html.erb
CREATE A NEW WRITER!
新しいライターを作成する!



<%= form_for @writer do |f| %>
<%= f.label :pen_name %>
<%= f.text_field :pen_name %>
<br>
<%= f.label :password %>
<%= f.text_field :password %>
<br>
<%= f.submit %>
<% end %>

app/views/writers/show.html.erb
Writer Show Page
<hr>
<hr>
Name: <%= @writer.pen_name %>
<br>
Language Written In: <% @writer.languages.each do |language| %>
<p><%= language.name %></p>
<% end %>
Stories: <% @writer.stories.each do |story| %>
<p><%= story.title %></p>
<% end %>
<br>
<%= link_to 'Edit Writer', edit_writer_path(@writer) %>
<%= link_to 'See All Writers', writers_path %>